language: node_js
dist: trusty
sudo: required
node_js:
- 9.5.0
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
addons:
  chrome: stable
before_deploy:
- npm run build
deploy:
  provider: npm
  email: harunurhan17@gmail.com
  skip_cleanup: true
  on:
    tags: true
    repo: harunurhan/is-valid-orcid-js
    branch: master
  api_key:
    secure: KSdwRCA5SEZYO8L0SgvLo0401LJXR8EGSbQKflJK5UOqo7XcdWxIFZv4OZING32v+fgI6/zk9sGXmRoW3329yxaeq+N10qUGvPPHCoj4+OxwMW2+bdOOaePO4RCUSeqJbf81mkUJbMJLGUa6lPZE8N6pfinZidz6v7orQFbkXV8qz9rQy0eO3ZaCuI37Xv6kJkR+w2w5M9hnYgIF5yAjPALg7Vurll1VAjQeQMDTpm08XouGKD8SyUSUGscEWWd+PmtR0htxuSO+FMyP/z5LMe+TnObCbpSHwCY+qd7cTsZDOuYAvKtNWLRy7H9IUM63ltpXGVxs7a9S+aHnu5m0+4ZoTdS2+WUh9aeQPDrYVyr2VsliteIMgyZMSomNBcJ8Q27/7lVrE4pCVTr3aQ/GQAQd4gjNrc19GsdYIv71lNUFUI8ChoDA58eUyYSvwtKO+nMbMM/Xav0HSoo+mPV+KNSheEG0sIAtzJNbu57YtMsyBUzVG8Jj05ihcB9l5ec0gjc9ykQgyaiYe/VEWYQH8z/WXLGsjI5khlxlKTokgm8KVtbUF/MwJZvA+d53HiWrLgnA5cHUE1P/tpy5cI7XydFtoGoVR5E5877a5yORALBnjUJZX9gIGbS4gs+q9gWRqn+kn87gxuo45wI+3QnL8CkV5DyWYcA+2hEUNN2VP14=
